version: "3.7"

services:
  lsish-hath:
    image: weirderest/lsish-hath:${DOCKER_TAG:?Please set your .env per the README}
    container_name: lsish-hath
    hostname: lsish-hath
    build:
      context: ./build/
      dockerfile: Dockerfile
    env_file:
      - ./.env
    expose:
      - ${HATH_PORT}
    ports:
      - "${HATH_PORT:?Please set your .env per the README}:${HATH_PORT}"
    volumes:
      - ${DIR_CONFIG:?Please set your .env per the README}:/config
      - ${DIR_DL:?Please set your .env per the README}:/dl
    restart: unless-stopped
